version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - home_security_DB__uri=postgresql://postgres:postgres@db:5432/home_security
      - home_security_DB__connect_args={}
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: home_security_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/home_security_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=home_security, home_security_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
